title: B3bieSec Team - Hack all my life also my love 💞
description: "A Full Developer | A Pentester System + CTF"
author:
  name: "B3bieSec"
  email: "B3bieSec@gmail.com"
  url: "http://ctfiuh.wordpress.com/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
